package pl.wsb.lab.medicalclinic.doctor;

public enum MedicalSpecialty {
    FAMILY_MEDICINE,
    INTERNAL_MEDICINE,
    PEDIATRICS,
    CARDIOLOGY,
    DERMATOLOGY,
    EMERGENCY_MEDICINE,
    GASTROENTEROLOGY,
    NEUROLOGY,
    OBSTETRICS_GYNECOLOGY,
    ONCOLOGY,
    OPHTHALMOLOGY,
    ORTHOPEDICS,
    OTOLARYNGOLOGY,
    PATHOLOGY,
    PSYCHIATRY,
    PULMONOLOGY,
    RADIOLOGY,
    RHEUMATOLOGY,
    SURGERY,
    UROLOGY
}